export const themeColors = {
  primary: '#a26235',
  secondaryText: '#6b7280',
  primaryText: '#111',
  background: '#fdfdfd',
  cardBackground: '#fff',
  ringBackground: '#e5e7eb',
  ringInactive: '#d1d5db',
  iconRed: '#ef4444',
  iconOrange: '#f97316',
  iconBlue: '#3b82f6',
  fabIcon: '#ffffff',
  navBorder: '#e5e7eb',
  inactiveNavText: '#9ca3af',
  emptyCardBackground: '#f9f8fd',
  gradientStart: '#f9fafb',
  gradientEnd: '#f3f4f6',
}; 